### ISSUE TITLE
[Bug?] Cannot read property '@schematics/angular:component' of undefined 

### ISSUE THREAD

**Issue by martinandersen3d** [LuisReinoso/vscode-ng-file-switcher#3]
**What works:**
- switch to ts, test, html

**What doesnt work:**
- switch to CSS/SCSS

**Expected behaviour:**
- Switch to the CSS/SCSS file in the same directory as the component?

example - Switch to this file:
`src/app/component/toolbar-top/toolbar-top.component.scss`

**Error:**
Cannot read property '@schematics/angular:component' of undefined 

---

## I maybe assume I'm doing something wrong?

---
thanks

![Peek 2021-01-05 00-55](https://user-images.githubusercontent.com/19984581/103591521-b32b2980-4ef0-11eb-8d0c-03dc6098c08f.gif)

![image](https://user-images.githubusercontent.com/19984581/103592719-136f9a80-4ef4-11eb-976b-ce70e034474e.png)

**Comment by LuisReinoso** [comment]
Hello @martinandersen3d. Thanks for report this issue This is related to #1 To read styles from angular.json. 

To fix this I would like to help me with two things.
- Could you share all your `angular.json` file please
- Could you check if you are using extension is using the version [v1.0.2](https://github.com/LuisReinoso/vscode-ng-file-switcher/releases/tag/v1.0.2)

Thanks a lot. I will try to fix this as soon I can. ;)

**Comment by martinandersen3d** [comment]
I'm still new to editing the angular.json.. so if you have a fix, please talk like I'm a noob :D But here we go:


```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "angular-frontend": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:application": {
          "strict": true
        },
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/angular-frontend",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/custom-theme.scss",
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "angular-frontend:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "angular-frontend:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "angular-frontend:build"
          }
        },
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "angular-frontend:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "angular-frontend:serve:production"
            }
          }
        }
      }
    }
  },
  "defaultProject": "angular-frontend"
}
```

Version:
![image](https://user-images.githubusercontent.com/19984581/103688736-8b8c9d80-4f92-11eb-8daf-7aa34225bed2.png)

**Comment by LuisReinoso** [comment]
I have runned e2e tests with your `angular.json` file.
Your file is very similar to [angular.json](https://github.com/LuisReinoso/vscode-ng-file-switcher/blob/master/workspaces/workspace-default-project/angular.json) included on testing workspace on version v1.0.2.

Could you reproduce this issue using the v1.0.2 please?.
I try to say switch from `app.component.ts` to `app.component.sccs` 
it should works on v1.0.2.

https://user-images.githubusercontent.com/7484215/103726777-c3521000-4fa7-11eb-8640-2567c8ce7ff4.mp4

**Comment by martinandersen3d** [comment]
I don't know what changed... but it works now... :smile:  :cry: 
The worst part is that I try to switch back to a older branch, where it used to break.. but it also works there :smile: 

Magic.

**Comment by LuisReinoso** [comment]
haha That's great!. 
The issue was my old version extension wasn't compatible with defaultProject config in `angular,json`

I hope this extension help you to improve and speed up your workflow. I will close this thread.
Thanks a lot.!
